[project]
name = "rl-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gymnasium>=1.1.1",
    "ipykernel>=6.29.5",
    "jupyterlab>=4.4.2",
    "pandas>=2.2.3",
    "stable-baselines3[extra]>=2.6.0",
]
